BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[User] (
    [id] INT NOT NULL IDENTITY(1,1),
    [name] NVARCHAR(1000),
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [User_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [User_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- CreateTable
CREATE TABLE [dbo].[Palette] (
    [id] INT NOT NULL IDENTITY(1,1),
    [number] INT NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Palette_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [Palette_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [Palette_number_key] UNIQUE NONCLUSTERED ([number])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
