BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Palette] (
    [id] INT NOT NULL IDENTITY(1,1),
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Palette_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [Palette_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
